import streamlit as st
import pandas as pd

def main():
    st.set_page_config(page_title="Radar Premium - AdrielAI", layout="wide")
    
    # FORÇADOR ULTRA LUXO CYBER-NEON COMPILADO (100% ALINHADO E EMBUTIDO)
    st.markdown("<style>header,[data-testid='stHeader']{background:transparent!important;display:none!important;}[data-testid='stAppViewContainer']{padding-top:0px!important;}html,body,[data-testid='stAppViewContainer'],.stApp{background-color:#030712!important;color:#f9fafb!important;}[data-testid='stSidebar'],section[data-testid='stSidebar'] div{background-color:#090d16!important;}[data-testid='stSidebar'] nav ul li div a span{color:#00ffcc!important;font-weight:bold!important;text-shadow:0 0 8px rgba(0,255,204,0.5)!important;}.stTextInput>div>div>input{background-color:#0f172a!important;color:#00ffcc!important;border:2px solid #1e293b!important;border-radius:8px!important;font-size:1.1rem!important;}.stTextInput>div>div>input:focus{border-color:#00ffcc!important;box-shadow:0 0 15px rgba(0,255,204,0.3)!important;}.stButton>button{background-color:#070b13!important;color:#f3f4f6!important;border:1px solid #1e293b!important;border-radius:6px!important;text-align:left!important;padding-left:15px!important;width:100%!important;height:42px!important;transition:all 0.2s!important;}.stButton>button:hover{border-color:#00ffcc!important;color:#00ffcc!important;box-shadow:0 0 10px rgba(0,255,204,0.2)!important;}[data-testid='stMetricContainer']{background:linear-gradient(135deg,#0f172a,#030712)!important;border:1px solid #1e293b!important;border-left:4px solid #00ffcc!important;padding:15px!important;border-radius:10px!important;}h1,h2,h3,h4,span,p,label,.stMarkdown p{color:#f3f4f6!important;}[data-testid='stNotification']{background-color:#0f172a!important;border:1px solid #1e293b!important;border-radius:10px!important;}div[data-testid='stVegaLiteChart'],.stVegaLiteChart{background:transparent!important;border:1px solid #1e293b!important;padding:10px!important;border-radius:8px!important;}svg,canvas,g,path,rect{background:transparent!important;}text,span{fill:#f3f4f6!important;color:#f3f4f6!important;font-family:monospace!important;}</style>", unsafe_allow_html=True)

    st.markdown('<h1 style="font-size: 2.5rem; font-weight: 900; color: #00ffcc; text-shadow: 0 0 15px rgba(0,255,204,0.4); margin-bottom: 5px;">💎 RADAR DE PRODUTOS PERPÉTUOS</h1>', unsafe_allow_html=True)
    st.write("Varredura automatizada e mapeamento analítico de ofertas de alta conversão nas plataformas internacionais.")
    st.info("🛰️ Sistema operando com Inteligência Preditiva Computacional. Auditoria ativa em tempo real.")
    st.markdown("---")

    if "produto_radar_ativo" not in st.session_state:
        st.session_state.produto_radar_ativo = "FitSpresso"

    col_esquerda, col_direita = st.columns([1.1, 1.0])

    # BANCO DE DADOS COMPACTADO ULTRA LINEAR (18 PRODUTOS REAIS DE AFILIADOS 2026)
    db = [
        {"id":"Alpilean","label":"📍 Alpilean | 🟢 ALTA - MONITORANDO","usa":"$1.70","uk":"$1.15","ca":"$1.30","au":"$1.20","nz":"$1.10","buscas":"32.100","cliques":"740","status":"🔵 SINAL AZUL: ESTÁVEL - VOLUME MODERADO SOB CONTROLE","cor":"#0066ff","fator":3,"dor":"Consumidores buscando queima calórica baseada na temperatura corporal interna celular. Frustrados com a falta de resultados em academias.","veredito":"Manter campanhas otimizadas fundo de funil segmentadas para o público britânico e canadense."},
        {"id":"Puravive","label":"⚡ Puravive | 🔥 ALTA - SUBINDO","usa":"$1.95","uk":"$1.30","ca":"$1.50","au":"$1.40","nz":"$1.25","buscas":"53.325","cliques":"1.355","status":"🟢 SINAL VERDE: LEILÃO LIMPO - EXCELENTE ESCALA","cor":"#00ffcc","fator":5,"dor":"Público-alvo buscando otimizar o tecido adiposo marrom (BAT). Sofrem com fadiga e baixa autoestima corporal.","veredito":"Ótimo momento para campanhas no Reino Unido (UK) e Canadá (CA). Use estruturas de Pre-Sell informativas."},
        {"id":"JavaBurn","label":"⚡ Java Burn | 🔥 ALTA - POTENTE","usa":"$1.80","uk":"$1.25","ca":"$1.40","au":"$1.30","nz":"$1.15","buscas":"45.120","cliques":"1.110","status":"🟡 SINAL AMARELO: CONCORRÊNCIA MÉDIA - OTIMIZAR PRODUTOR","cor":"#ffcc00","fator":4,"dor":"Consumidores que querem transformar a rotina matinal do café em um queimador de gordura automático contra cansaço crônico.","veredito":"Campanhas mistas de Google Search e YouTube Ads performam melhor. Focar em cookies de alta renda nos EUA."},
        {"id":"FitSpresso","label":"⚡ FitSpresso | 🔥 ALTA - ACELERADO","usa":"$2.10","uk":"$1.45","ca":"$1.65","au":"$1.55","nz":"$1.35","buscas":"62.410","cliques":"1.840","status":"🟢 SINAL VERDE: LEILÃO COMPETITIVO - ALTO ROI EM FUNDO DE FUNIL","cor":"#00ffcc","fator":6,"dor":"Compradores gringos desesperados por perda de peso natural através da aceleração metabólica do café sem dietas restritivas.","veredito":"Anunciar fortemente no Google Ads em correspondência exata para termos de intenção comercial direta nos EUA e Reino Unido."},
        {"id":"ProDentim","label":"⚡ ProDentim | 🔥 ALTA - SEGURO","usa":"$1.65","uk":"$1.10","ca":"$1.30","au":"$1.20","nz":"$1.05","buscas":"39.400","cliques":"980","status":"🟢 SINAL VERDE: LEILÃO ESTÁVEL - CPC ACESSÍVEL","cor":"#00ffcc","fator":4,"dor":"Leads com problemas de sensibilidade dentária, gengivas sangrentas e mau hálito. Medo de tratamentos caros.","veredito":"Anuncie no Bing Ads além do Google Ads. O público de faixa etária mais avançada converte muito rápido nesta oferta."},
        {"id":"LivPure","label":"⚡ Liv Pure | 🔥 ALTA - EXPANDINDO","usa":"$1.90","uk":"$1.35","ca":"$1.45","au":"$1.35","nz":"$1.20","buscas":"42.150","cliques":"1.040","status":"🟡 SINAL AMARELO: DENSIDADE ELEVADA - REQUER COPY EMOCIONAL","cor":"#ffcc00","fator":3,"dor":"Indivíduos com sobrepeso que sofrem de sobrecarga hepática devido a toxinas cotidianas e inchaço contínuo.","veredito":"Foque no tráfego via Advertorial estruturado que educa o lead sobre a desintoxicação do fígado antes da oferta."},
        {"id":"Denticore","label":"⚡ Denticore | 🔥 ALTA - RECENTE","usa":"$1.75","uk":"$1.20","ca":"$1.35","au":"$1.25","nz":"$1.10","buscas":"41.200","cliques":"1.010","status":"🟢 SINAL VERDE: LEILÃO NOVO - BAIXA CONCORRÊNCIA EM EXATA","cor":"#00ffcc","fator":5,"dor":"Pessoas propensas a cáries e oxigenação gengival deficiente buscando reconstrução antisséptica profunda em gotas ou cápsulas.","veredito":"Escalar em correspondência exata para termos de marca institucionais fundo de funil. CPC limpo."},
        {"id": "NaganoTonic","label":"⚡ Nagano Tonic | 🔥 ALTA - SUBINDO","usa":"$2.00","uk":"$1.40","ca":"$1.60","au":"$1.50","nz":"$1.30","buscas":"48.600","cliques":"1.220","status":"🟢 SINAL VERDE: TENDÊNCIA ORIENTAL - TAXA DE CLIQUES EM ASCENSÃO","cor":"#00ffcc","fator":5,"dor":"Público maduro buscando elixires japoneses de longevidade e queima de gordura visceral profunda bloqueada pelo envelhecimento.","veredito":"Anunciar em listas de públicos semelhantes (Lookalike) no YouTube Ads direcionando para página pré-sell agressiva."},
        {"id":"SugarDefender","label":"⚡ Sugar Defender | 🔥 ALTA - QUENTE","usa":"$2.30","uk":"$1.60","ca":"$1.85","au":"$1.70","nz":"$1.50","buscas":"51.800","cliques":"1.490","status":"🔴 SINAL VERMELHO: LEILÃO SATURADO - REQUER ESTRUTURA PRÓPRIA BLINDADA","cor":"#ff0055","fator":6,"dor":"Leads na faixa de 40 a 70 anos sofrendo com oscilações de glicose no sangue e cansaço extremo pós-refeição.","veredito":"Fundo de funil altamente competitivo. Evite mandar tráfego direto! Use páginas clonadas e blindadas locais."},
        {"id":"Cortexi","label":"🛡️ Cortexi | 🔵 NORMAL - ESTÁVEL","usa":"$1.50","uk":"$0.95","ca":"$1.15","au":"$1.05","nz":"$0.90","buscas":"28.300","cliques":"620","status":"🔵 SINAL AZUL: ESCALA REGULAR - LEILÃO LIVRE E TRANQUILO","cor":"#0066ff","fator":2,"dor":"Idosos sofrendo de zumbido no ouvido (tinnitus) constante, tirando o foco diário e gerando ansiedade profunda.","veredito":"Use termos focados no alívio de sintomas auditivos. Excelente ROI em campanhas de Bing Search pelo baixo CPC."},
        {"id":"ZenCortex","label":"🛡️ ZenCortex | 🔵 NORMAL - ESTÁVEL","usa":"$1.60","uk":"$1.00","ca":"$1.20","au":"$1.10","nz":"$0.95","buscas":"31.200","cliques":"710","status":"🔵 SINAL AZUL: MERCADO PERPÉTUO - FLUXO DIÁRIO CONSTANTE","cor":"#0066ff","fator":2,"dor":"Leads buscando proteção para a saúde do cérebro e melhora da acuidade auditiva natural rejeitando químicos pesados.","veredito":"Anunciar em correspondência de frase direcionando para páginas de Pre-Sell no modelo de Review de Autoridade."},
        {"id":"Kerassentials","label":"🛡️ Kerassentials | 🔵 NORMAL - MONITORADO","usa":"$1.45","uk":"$0.90","ca":"$1.10","au":"$1.00","nz":"$0.85","buscas":"25.400","cliques":"540","status":"🔵 SINAL AZUL: OFERTA PERPÉTUA SAZONAL - EXCELENTE NO VERÃO","cor":"#0066ff","fator":3,"dor":"Mulheres e homens envergonhados por fungos severos nas unhas e descamação dolorosa na pele dos pés.","veredito":"Focar tráfego em redes nativas (Taboola/Outbrain) e Google Imagens. Apelo visual forte resolve a conversão rápido."},
        {"id":"SynapseXT","label":"🛡️ Synapse XT | 🔵 NORMAL - MONITORADO","usa":"$1.55","uk":"$0.95","ca":"$1.15","au":"$1.05","nz":"$0.90","buscas":"24.100","cliques":"510","status":"🔵 SINAL AZUL: VOLUME ESTÁVEL - BAIXA VOLATILIDADE MENSAL","cor":"#0066ff","fator":2,"dor":"Consumidores buscando sinergia cerebral para reconectar sinapses enfraquecidas e combater perda de memória precoce.","veredito":"Manter anúncios institucionais ativos em correspondência exata para capturar intenção de compra remanescente."},
